version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - ./install_all.sh
    #finally:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - ./deploy_all.sh
    #finally:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
