version: 0.2

phases:
  install:
    commands:
      - cd hip-edit-server
      - npm install
      - cd ../
  pre_build:
    commands:
      - cd hip-edit-server
      - npm test
      - cd ../
  build:
    commands:
      - cd hip-edit-server
      - npm run build-lambda
      - cd ../
